# Generated by Django 6.0.3 on 2026-03-22 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre du cours')),
                ('enseignant', models.CharField(max_length=100, verbose_name='Enseignant')),
                ('date_publication', models.DateField(verbose_name='Date de publication')),
            ],
            options={
                'verbose_name': 'Cours',
                'verbose_name_plural': 'Cours',
                'ordering': ['-date_publication'],
            },
        ),
    ]
